version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  heroku: circleci/heroku@1.0.1
jobs:
  tests:
    docker:
      - image: aotarola/node-alpine-basics
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm t

      - codecov/upload:
          file: coverage/*.json
          flags: frontend
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - tests
      - deploy:
          filters:
            branches:
              only: master
